services:
  - docker
env:
  global:
    DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH" ; fi)
    DOCKER_IMAGE_NAME="sifive/environment-blockci"
    DOCKER_CACHE_IMAGE=sifive/environment-blockci:latest

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Build Wit Dockerfile"
      script: ./build_image.sh

    - stage: deploy
      name: "Deploy Docker Image"
      # For pull requests, branch is the base branch (on PR to master: branch = master)
      if: tag IS present OR (branch = master AND type = push)
      script:
        - ./build_image.sh
        - ./push_image.sh
